#!/usr/bin/env bash
# This script changes the home IP address and redirects facebook.com to Google's DNS server.

sudo sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts

sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts