#!/usr/bin/env bash
# This script changes the home IP address and redirects facebook.com to Google's DNS server.

cp /etc/hosts /tmp/hosts
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
echo "127.0.0.1 $(hostname)" >> /tmp/hosts
cp /tmp/hosts /etc/hosts